# Generated by Django 4.2.16 on 2025-01-30 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('man', '0004_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
